name: 'Run on Arm Virtual Target on AMI'
description: 'Load executable file to an Arm Virtual Target to execute'
inputs:
  access_key_id:
    description: 'access key id for connection'
    required: true
    default: ''
  ami_id:
    description: 'VHT AMI ID desired'
    required: false
    default: ''
  aws_region:
    description: 'aws region'
    required: true
    default: 'eu-west-1'
  iam_role:
    description: 'IAM role name'
    required: false
    default: ''
  instance_id:
    description: 'instance id for connection'
    required: false
    default: ''
  instance_type:
    description: 'EC2 instance type'
    required: false
    default: 't2.micro'
  s3_bucket_name:
    description: S3 Bucket to upload files used on EC2 instance
    required: true
    default: ''
  secret_access_key:
    description: 'secret access key for connection'
    required: true
    default: ''
  security_group_id:
    description: 'security group for EC2 instance'
    required: false
    default: ''
  session_token:
    description: 'session token if you need'
    required: false
    default: ''
  ssh_key_name:
    description: 'optional SSH Key name'
    required: false
    default: ''
  subnet_id:
    description: 'subnet_id for the EC2 instance'
    required: false
    default: ''
  terminate_ec2_instance:
    description: 'should ec2 instance be terminated after running it?'
    required: false
    default: 'false'
  vht_in:
    description: 'path to test_suite'
    required: true
outputs:
  vht_out: # output will be available to future steps
    description: 'path to results'

runs:
  using: 'node12'
  main: 'dist/index.js'
